hsv_filter_node:
  ros__parameters:
    use_sim_time: true
    min_h: 31
    max_h: 180
    min_s: 179
    max_s: 255
    min_v: 218
    max_v: 255

detection_to_3d_from_depth_node:
  ros__parameters:
    use_sim_time: true

