name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 2 Jazzy
        uses: ros-tooling/setup-ros@v0.7
        with:
          distribution: jazzy

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions

      - name: Build workspace
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --event-handlers console_cohesion+

